version: "3.9"
services:
  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
    container_name: lore-conv-api
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    volumes:
      - ../../models:/app/models
