version: "3.9"
services:
  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
    container_name: lore-conv-api
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    volumes:
      - ../../models:/app/models

  qdrant:
    image: qdrant/qdrant:v1.8.3
    restart: always
    ports:
      - "6333:6333" 
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  qdrant_data: