name: CD
on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/lore-conv-eval-api:${GITHUB_REF_NAME#refs/tags/}
          docker build -t $IMAGE -f infrastructure/docker/Dockerfile .
          docker push $IMAGE
      - name: Echo image URL
        run: echo "Published $IMAGE"