name: CI
on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - name: Install deps (runtime + dev)
        run: poetry install --with dev
      - name: Static checks
        run: |
          poetry run ruff check .
          poetry run black --check .
          poetry run mypy app/ services/
      - name: Run tests
        run: poetry run pytest --cov=app --cov=services
      - name: Build Docker image (cache‑only)
        run: docker build -t lore-conv-api:ci -f infrastructure/docker/Dockerfile .